export interface ProgramDay {
  day: number
  task: string
  category: string
}

export interface Program {
  id: string
  title: string
  subtitle: string
  icon: string
  durationDays: number
  category: string
  days: ProgramDay[]
}

export const PROGRAMS: Program[] = [
  {
    id: 'confidence-30',
    title: '30-Day Confidence Bootcamp',
    subtitle: 'Become the man who takes up space.',
    icon: '🗣️',
    durationDays: 30,
    category: 'confidence',
    days: [
      { day: 1,  task: 'Make eye contact with 5 strangers today. Hold it until they look away first.',                           category: 'confidence' },
      { day: 2,  task: 'Give 3 genuine compliments to strangers. Make each one specific.',                                       category: 'confidence' },
      { day: 3,  task: 'Say hello to 5 strangers. Just hello. That is it.',                                                     category: 'confidence' },
      { day: 4,  task: 'Take a 60-second cold shower. Do not hesitate. Get straight in.',                                       category: 'confidence' },
      { day: 5,  task: 'Ask a stranger a genuine question. Listen to the full answer.',                                          category: 'confidence' },
      { day: 6,  task: 'Speak up in every conversation you have today. State your opinion clearly.',                             category: 'confidence' },
      { day: 7,  task: 'Approach someone you find attractive and give them a sincere compliment.',                               category: 'confidence' },
      { day: 8,  task: 'Record yourself talking for 2 minutes about anything. Watch it back.',                                  category: 'confidence' },
      { day: 9,  task: 'Start a conversation with 3 strangers today. Keep each one going for at least 60 seconds.',             category: 'confidence' },
      { day: 10, task: '2-minute cold shower from the very start. No warm water at all.',                                       category: 'confidence' },
      { day: 11, task: 'Ask for something you expect to be refused. Handle the no without flinching.',                          category: 'confidence' },
      { day: 12, task: 'Tell 5 strangers something specific you genuinely noticed about them.',                                  category: 'confidence' },
      { day: 13, task: 'Introduce yourself to 3 new people today. Get their names.',                                            category: 'confidence' },
      { day: 14, task: 'Tell a story to a group and hold their attention all the way to the end.',                              category: 'confidence' },
      { day: 15, task: 'Approach 2 people you find attractive. Introduce yourself and have a real conversation.',               category: 'confidence' },
      { day: 16, task: 'Record a 3-minute video of yourself on a topic you know well. Critique it honestly.',                   category: 'confidence' },
      { day: 17, task: '3-minute cold shower. Control your breathing. Stay completely calm.',                                   category: 'confidence' },
      { day: 18, task: 'Get rejected twice on purpose. Ask for something you think they will say no to.',                       category: 'confidence' },
      { day: 19, task: 'Walk into a room and introduce yourself to someone you do not know.',                                   category: 'confidence' },
      { day: 20, task: 'Give 10 compliments to strangers throughout the day. Make each one land.',                              category: 'confidence' },
      { day: 21, task: 'Lead a conversation in a group. Keep it going. Do not let it die.',                                     category: 'confidence' },
      { day: 22, task: 'Make a bold ask today that has real stakes. Do not water it down.',                                     category: 'confidence' },
      { day: 23, task: 'Start 5 conversations with strangers. Get at least 3 names.',                                           category: 'confidence' },
      { day: 24, task: 'Approach 3 people you find attractive today. Get at least 1 number.',                                   category: 'confidence' },
      { day: 25, task: 'Speak first in every group situation you find yourself in today.',                                      category: 'confidence' },
      { day: 26, task: 'Get rejected 3 times by strangers. Notice how small the discomfort is.',                               category: 'confidence' },
      { day: 27, task: 'Walk into a social situation knowing no one. Leave knowing at least 5 people.',                         category: 'confidence' },
      { day: 28, task: '3-minute cold shower. Smile while you do it.',                                                         category: 'confidence' },
      { day: 29, task: 'Make 10 people feel genuinely good about themselves today. Strangers only.',                            category: 'confidence' },
      { day: 30, task: 'Write down who you were on Day 1 vs who you are now. The difference is real.',                         category: 'confidence' },
    ],
  },
  {
    id: 'morning-21',
    title: '21-Day Morning Warrior',
    subtitle: 'Win the morning. Win the day.',
    icon: '☀️',
    durationDays: 21,
    category: 'lifestyle',
    days: [
      { day: 1,  task: 'Wake at your planned time. No snooze. Drink water immediately.',                                        category: 'lifestyle' },
      { day: 2,  task: 'Wake on time. Drink water. Do 5 minutes of movement before touching your phone.',                      category: 'lifestyle' },
      { day: 3,  task: 'Wake on time. Cold water on your face. Write 3 priorities before anything else.',                      category: 'lifestyle' },
      { day: 4,  task: 'Wake on time. 5-minute stretch. No social media until you have completed 1 task.',                     category: 'lifestyle' },
      { day: 5,  task: 'Wake 15 minutes earlier than usual. Use the time for silence and planning.',                           category: 'lifestyle' },
      { day: 6,  task: 'Wake on time. Write what you are grateful for before you do anything else.',                           category: 'lifestyle' },
      { day: 7,  task: 'Full morning routine: wake, water, move, journal, priorities. No shortcuts.',                          category: 'lifestyle' },
      { day: 8,  task: 'Wake 30 minutes earlier. Use the time for reading or learning.',                                       category: 'lifestyle' },
      { day: 9,  task: 'Morning protocol before touching your phone. Non-negotiable.',                                         category: 'lifestyle' },
      { day: 10, task: 'Wake on time. 10 minutes of movement. Set your intention for the day out loud.',                       category: 'lifestyle' },
      { day: 11, task: 'Wake 30 minutes earlier. Cold shower. Write your top 3 wins from yesterday.',                          category: 'lifestyle' },
      { day: 12, task: 'Full protocol. Write down 1 thing that would make today a success.',                                   category: 'lifestyle' },
      { day: 13, task: 'Wake 45 minutes earlier than your usual time. No phone for the first hour.',                           category: 'lifestyle' },
      { day: 14, task: 'Two weeks in. Full review: what has changed about your mornings?',                                     category: 'lifestyle' },
      { day: 15, task: 'Wake at 6am regardless of when you slept. Full protocol.',                                             category: 'lifestyle' },
      { day: 16, task: 'Morning protocol. Spend 10 minutes on your most important goal before work.',                          category: 'lifestyle' },
      { day: 17, task: 'Wake early. 15 minutes of physical movement. Set your tone for the day.',                              category: 'lifestyle' },
      { day: 18, task: 'Full morning protocol completed before 7am. Start the day on your terms.',                             category: 'lifestyle' },
      { day: 19, task: 'Wake early. Review your goals. Write what you will do today to move toward them.',                     category: 'lifestyle' },
      { day: 20, task: 'Full protocol. No phone until you have written, moved, and eaten.',                                    category: 'lifestyle' },
      { day: 21, task: 'You built the habit. Write down your new morning protocol and commit to it permanently.',              category: 'lifestyle' },
    ],
  },
  {
    id: 'physical-30',
    title: '30-Day Physical Forge',
    subtitle: 'Build the body. Build the discipline.',
    icon: '🏋️',
    durationDays: 30,
    category: 'physical',
    days: [
      { day: 1,  task: '5-min: 2x10 push-ups, 2x10 squats, 20s plank. Rest freely.',                                         category: 'physical' },
      { day: 2,  task: '5-min: 3x10 push-ups, 3x12 squats, 30s plank. 20s rest between sets.',                                category: 'physical' },
      { day: 3,  task: '5-min: 2x10 lunges each leg, 2x10 crunches, 20s plank.',                                              category: 'physical' },
      { day: 4,  task: '5-min: 30s jumping jacks, 30s push-ups, 30s squats, 30s rest. x2.',                                   category: 'physical' },
      { day: 5,  task: '5-min: 3x12 push-ups, 3x15 squats, 3x10 crunches, 30s plank.',                                       category: 'physical' },
      { day: 6,  task: '5-min: 6x30s run on spot at 70%, 20s rest each.',                                                     category: 'physical' },
      { day: 7,  task: '5-min: 60s deep squat hold, 30s hip stretch each side, 30s plank. x2.',                               category: 'physical' },
      { day: 8,  task: '5-min: 3x15 push-ups, 3x20 squats, 45s plank. 15s rest.',                                            category: 'physical' },
      { day: 9,  task: '5-min: 40s burpees, 20s rest, 40s mountain climbers, 20s rest. x3.',                                  category: 'physical' },
      { day: 10, task: '5-min: 3x20 crunches, 3x15 leg raises, 2x40s plank.',                                                 category: 'physical' },
      { day: 11, task: '5-min: 4x15 push-ups, 4x15 squats, 60s plank. 15s rest.',                                            category: 'physical' },
      { day: 12, task: '5-min AMRAP: 10 push-ups, 15 squats, 20s plank. Max rounds.',                                         category: 'physical' },
      { day: 13, task: '5-min: 8x30s sprint on spot, 7s rest. Push every interval.',                                          category: 'physical' },
      { day: 14, task: '5-min flow: 10 Hindu push-ups, 10 world greatest stretch each side, 60s squat hold.',                  category: 'physical' },
      { day: 15, task: '5-min: 4x20 push-ups, 4x20 squats, 2x60s plank. 10s rest.',                                          category: 'physical' },
      { day: 16, task: '5-min: 45s burpees, 45s push-ups, 45s jump squats, 15s rest each. x2.',                               category: 'physical' },
      { day: 17, task: '5-min: 4x20 bicycle crunches, 4x15 leg raises, 2x60s plank.',                                        category: 'physical' },
      { day: 18, task: '5-min: 4x20 jump squats, 4x15 lunges each leg, 45s wall sit.',                                        category: 'physical' },
      { day: 19, task: '5-min: 10x30s max sprint on spot, 0s rest. Do not slow down.',                                        category: 'physical' },
      { day: 20, task: '5-min AMRAP: 15 push-ups, 20 squats, 30s plank. Max rounds.',                                         category: 'physical' },
      { day: 21, task: '5-min: 4x20 diamond push-ups, 4x20 tricep dips, 3x20s pike hold.',                                    category: 'physical' },
      { day: 22, task: '5-min AMRAP: 20 V-ups, 20 leg raises, 60s plank. No rest.',                                           category: 'physical' },
      { day: 23, task: '5-min: 6x35s all-out sprint, 15s rest each. Push every one.',                                         category: 'physical' },
      { day: 24, task: '5-min AMRAP: 20 jump squats, 12 split squats per leg, 60s wall sit.',                                  category: 'physical' },
      { day: 25, task: '5-min flow x2: 5 burpees, 10 Hindu push-ups, world greatest stretch, 60s squat.',                     category: 'physical' },
      { day: 26, task: '5-min: 8x30s max effort sprint, 8s rest. Lungs must be burning.',                                     category: 'physical' },
      { day: 27, task: '5-min AMRAP: 10 burpees, 15 push-ups, 20 jump squats. Max rounds, no mercy.',                        category: 'physical' },
      { day: 28, task: '5-min: 4x25 push-ups, 4x25 squats, 2x60s plank, 3x20s pike hold.',                                   category: 'physical' },
      { day: 29, task: '5-min: 10x27s absolute max sprint, 3s rest. Fastest you have ever moved.',                            category: 'physical' },
      { day: 30, task: 'Final day. Repeat Day 1 and compare. You are not the same person.',                                   category: 'physical' },
    ],
  },
]
